version: '3'
services:
  redis1:
    image: redis
    ports:
      - "6379:6379"
    container_name: "redis1"
    networks: 
      - dev
  mysql1:
    image: centos/mysql-80-centos7
    environment:
      - MYSQL_ROOT_PASSWORD=root
     
    
    ports: 
      - "3306:3306"
    container_name: "mysql1"
    networks: 
      - dev
  web1:
    image: mjweb/dockermage:v1
    ports: 
      - "80:80"
    container_name: "web1"
    
    volumes:
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
      - ./auth.json:/home/magento/.composer/auth.json
      - ./auth.json:/root/.composer/auth.json
      - ./html/:/var/www/html/

    networks: 
      - dev
      - pro

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
    ports:
      - "9200:9200"

    networks:
      - dev
      - pro

networks:
  dev:
    driver: bridge
  pro:
    driver: bridge
